steps:
- name: gcr.io/cloud-builders/gcloud
  args: ["builds", "submit", "--pack", "image=gcr.io/$PROJECT_ID/elastic-cluster:$BRANCH_NAME"]
- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - elastic-cluster
  - --image=gcr.io/$PROJECT_ID/elastic-cluster:$BRANCH_NAME
  - --region=us-central1
  - --revision-suffix=$SHORT_SHA
 #- --no-traffic
  - --cpu=1
  - --memory=1G
  - --min-instances=1
  - --max-instances=10
  - --allow-unauthenticated
